---
dependency:
  name: galaxy

ansible:
  verbose: v
  playbook: tests/playbook-test.yml

driver:
  name: docker

docker:
  containers:
    - name: test-ssh-keys
      image: centos
      image_version: 7
      privileged: True
      command: '/usr/lib/systemd/systemd'

verifier:
  name: testinfra
